export const CREATE_CATEGORIES = "CREATE_CATEGORIES";
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_ALL_CATEGORIES = "DELETE_ALL_CATEGORIES";

//designer-home-page
export const GET_TOP_CATEGORY = "GET_TOP_CATEGORY";
export const GET_POPULAR_CATEGORY = "GET_POPULAR_CATEGORY";
export const GET_TOP_TRENDING = "GET_TOP_TRENDING";
export const GET_SUIT_WEAR = "GET_SUIT_WEAR";
export const GET_TOP_DESIGNERS = "GET_TOP_DESIGNERS";
export const GET_TOP_SEASON_OFFERS = "GET_TOP_SEASON_OFFERS";
export const GET_HAND_MADE_CLOTHES = "GET_HAND_MADE_CLOTHES";

export const GET_CATEGORY_GROUP = "GET_CATEGORY_GROUP";
export const GET_CATEGORY_SUBGROUP = "GET_CATEGORY_SUBGROUP";

export const GET_CUSTOMER_REVIEWS = "GET_CUSTOMER_REVIEWS";

//Authentication
export const SIGNUP_CREDS = "SIGNUP_CREDS";
export const LOGIN_CREDS = "LOGIN_CREDS";
export const USER_DATA = "USER_DATA";

//Men's Wear
export const MENS_WEAR_SLIDER = "MENS_WEAR_SLIDER";
export const MENS_WEAR_CAT = "MENS_WEAR_CAT";
export const MENS_WEAR_SUBGRP = "MENS_WEAR_SUBGRP";
export const SELECTED_SUB_GRP = "SELECTED_SUB_GRP";
export const MENS_ACTIVE_PRODUCT = "MENS_ACTIVE_PRODUCT";
export const NEW_COLLECTION = "NEW_COLLECTION";
export const TOP_DESIGNERS = "TOP_DESIGNERS";
export const STYLISH_RECOMMEND = "STYLISH_RECOMMEND";
export const MOST_LOVED = "MOST_LOVED";
export const ALL_THAT_YOU_WANT = "ALL_THAT_YOU_WANT";
export const TOP_OFFERS = "TOP_OFFERS";
export const CELIBRITY_STYLE = "CELIBRITY_STYLE";
export const GET_BANNER = "GET_BANNER";

//Offers
export const SECTION1_SLIDERS = "SECTION1_SLIDERS";
export const SECTION2_TOP_OFFERS = "SECTION1_TOP_OFFERS";

//Measurement

export const GET_ALL_MEASUREMENTS = "GET_ALL_MEASUREMENTS";
export const GET_SINGLE_MEASUREMENT = "GET_SINGLE_MEASUREMENT";
export const DELETE_MEASUREMENT = "DELETE_MEASUREMENT";
export const SAVE_MEASUREMENT_REQUEST = "SAVE_MEASUREMENT_REQUEST";
export const SAVE_MEASUREMENT_SUCCESS = "SAVE_MEASUREMENT_SUCCESS";
export const SAVE_MEASUREMENT_FAIL = "SAVE_MEASUREMENT_FAIL";
export const GENDER = "GENDER";
export const BASIC_DETAILS = "BASIC_DETAILS";
export const UPPER_BODY = "UPPER_BODY";
export const LOWER_BODY = "LOWER_BODY";
export const BASIC_ID = "BASIC_ID";

// orders
export const ORDER_SUMM = "ORDER_SUMM";
export const TRACK_ORDER_REQUEST = "TRACK_ORDER_REQUEST";
export const TRACK_ORDER_SUCCESS = "TRACK_ORDER_SUCCESS";
export const TRACK_ORDER_FAILED = "TRACK_ORDER_FAILED";
export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAI_SUCCESS";
export const ORDER_DETAIL_FAILED = "ORDER_DETAI_FAILED";

//payment
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";

//adress
export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILED = "GET_ADDRESS_FAILED";

//Profile
export const ADDRESS = "ADDRESS";
export const ORDERS = "ORDERS";
export const REVIEWS = "REVIEWS";
export const GET_DESIGNERS = "GET_DESIGNERS";

//Wishlist Page
export const GET_WISHLIST = "GET_WISHLIST";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const CLEAR_WISHLIST_UPDATE = "CLEAR_WISHLIST_UPDATE";
export const REMOVE_FROM_WISHLIST_REQUEST = "REMOVE_FROM_WISHLIST_REQUEST";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAILED = "REMOVE_FROM_WISHLIST_FAILED";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

//My Bag Page
export const GET_CART = "GET_CART";
export const ADD_TO_BAG = "ADD_TO_BAG";
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILED = "REMOVE_FROM_CART_FAILED";

//Coupons
export const GET_COUPONS_REQUEST = "GET_COUPONS_REQUEST";
export const GET_COUPONS_SUCCESS = "GET_COUPONS_SUCCESS";
export const GET_COUPONS_FAILED = "GET_COUPONS_FAILED";
export const APPLY_COUPONS_REQUEST = "APPLY_COUPONS_REQUEST";
export const APPLY_COUPONS_SUCCESS = "APPLY_COUPONS_SUCCESS";
export const APPLY_COUPONS_FAILED = "APPLY_COUPONS_FAILED";

//User Authentication
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN = "LOGIN";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const LOAD_USER = "LOAD_USER";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";

//Filter
export const GET_FILTER_LIST = "GET_FILTER_LIST";
export const GET_FILTERED_PRODUCT = "GET_FILTERED_PRODUCT";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";

//Products
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILED = "GET_PRODUCT_DETAILS_FAILED";
export const GET_SIMILAR_PRODUCTS_REQUEST = "GET_SIMILAR_PRODUCTS_REQUEST";
export const GET_SIMILAR_PRODUCTS_SUCCESS = "GET_SIMILAR_PRODUCTS_SUCCESS";
export const GET_SIMILAR_PRODUCTS_FAILED = "GET_SIMILAR_PRODUCTS_FAILED";

//filter
export const SET_FILTER_DATA = "SET_FILTER_DATA";
export const SET_FILTER_CLEAR = "SET_FILTER_CLEAR";
export const CLEAR_FILTER_DATA = "CLEAR_FILTER_DATA";

//address
export const GET_MY_ADDRESSES_REQUEST = "GET_MY_ADDRESSES_REQUEST";
export const GET_MY_ADDRESSES_SUCCESS = "GET_MY_ADDRESSES_SUCCESS";
export const GET_MY_ADDRESSES_FAILED = "GET_MY_ADDRESSES_FAILED";
export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED";

//errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
