export const CREATE_CATEGORIES = "CREATE_CATEGORIES";
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_ALL_CATEGORIES = "DELETE_ALL_CATEGORIES";

//designer-home-page
export const GET_TOP_CATEGORY = "GET_TOP_CATEGORY";
export const GET_POPULAR_CATEGORY = "GET_POPULAR_CATEGORY";
export const GET_TOP_TRENDING = "GET_TOP_TRENDING";
export const GET_SUIT_WEAR = "GET_SUIT_WEAR";
export const GET_TOP_DESIGNERS = "GET_TOP_DESIGNERS";
export const GET_TOP_SEASON_OFFERS = "GET_TOP_SEASON_OFFERS";
export const GET_HAND_MADE_CLOTHES = "GET_HAND_MADE_CLOTHES";

//Authentication
export const SIGNUP_CREDS = "SIGNUP_CREDS";
export const LOGIN_CREDS = "LOGIN_CREDS";
export const USER_DATA = "USER_DATA";

//Men's Wear
export const MENS_WEAR_SLIDER = "MENS_WEAR_SLIDER";
export const MENS_WEAR_CAT = "MENS_WEAR_CAT";
export const MENS_WEAR_SUBGRP = "MENS_WEAR_SUBGRP";
export const SELECTED_SUB_GRP = "SELECTED_SUB_GRP";
export const MENS_ACTIVE_PRODUCT = "MENS_ACTIVE_PRODUCT";
export const NEW_COLLECTION = "NEW_COLLECTION";
export const TOP_DESIGNERS = "TOP_DESIGNERS";
export const STYLISH_RECOMMEND = "STYLISH_RECOMMEND";
export const MOST_LOVED = "MOST_LOVED";
export const ALL_THAT_YOU_WANT = "ALL_THAT_YOU_WANT";
export const TOP_OFFERS = "TOP_OFFERS";
export const CELIBRITY_STYLE = "CELIBRITY_STYLE";