export const CREATE_CATEGORIES = "CREATE_CATEGORIES";
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_ALL_CATEGORIES = "DELETE_ALL_CATEGORIES";

//designer-home-page
export const GET_TOP_CATEGORY = "GET_TOP_CATEGORY";
export const GET_POPULAR_CATEGORY = "GET_POPULAR_CATEGORY";
export const GET_TOP_TRENDING = "GET_TOP_TRENDING";
export const GET_SUIT_WEAR = "GET_SUIT_WEAR";
