// export const navItems = [
//   { name: 'Designers', icon: designersIcon, path: '/designers/' },
//   { name: 'Measurement', icon: mesurementIcon, path: '/measurement/' },
//   { name: 'Simulated (Mirror)', icon: simulatedIcon, path: '/simulated/' },
//   { name: 'Customized ', icon: customizedIcon, path: '/customized/' },
//   { name: 'Offers', icon: offersIcon, path: '/offers/' },
//   { name: 'Subscription', icon: subscriptionIcon, path: '/subscription/' },
//   { name: 'Reward', icon: rewardIcon, path: '/reward/' },
//   { name: 'Orders', icon: ordersIcon, path: '/orders/' },
//   { name: 'My Reviews', icon: myReviewsIcon, path: '/review/' },
//   { name: 'Wishlist', icon: wishlistIcon, path: '/wishlist/' },
//   { name: 'My Addresses', icon: myAddressIcon, path: '/myaddresses/' },
//   { name: 'Payments', icon: paymentsIcon, path: '/payments/' },
//   { name: 'Chat Expert', icon: chatExpertIcon, path: '/chatexpert' },
//   { name: 'About us', icon: aboutUsIcon, path: '/aboutus/' },
//   { name: 'Contact Us', icon: contactUsIcon, path: '/contactus/' },
//   { name: 'Support', icon: supportIcon, path: '/support/' },
//   { name: 'Logout', icon: logoutIcon, fun: true },
// ];
